[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
name = "dashl"
version = "0.0.0"

[dependencies]
futures = "0.1.23"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
hyper = "0.12.7"
hyper-tls = "0.3.0"
