[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
name = "dashl"
version = "0.0.0"

[dependencies]
hyper = "0.10.9"
hyper-native-tls = "0.2.2"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"
